#!/usr/bin/env python3

import os
import sys
import shutil

"""Script to uninstall AsciiDoc3. To run 'uninstallscript',
   make it executable and start as root/su. See UNINSTALL.
   """

# remove directory '/usr/share/asciidoc3' and all files
if os.path.isdir("/usr/share/asciidoc3"):
    if not os.access("/usr/share/asciidoc3", os.F_OK | os.W_OK):
        print("no access to /usr/share/asciidoc3")
        print("are you root?")
        sys.exit(1)
    else:
        shutil.rmtree("/usr/share/asciidoc3")

# remove directory '/etc/asciidoc3' and all files
if os.path.isdir("/etc/asciidoc3"):
    if not os.access("/etc/asciidoc3", os.F_OK | os.W_OK):
        print("no access to /etc/asciidoc3")
        sys.exit(1)
    else:
        shutil.rmtree("/etc/asciidoc3")

# remove manpages
if not os.access("/usr/share/man/man1/asciidoc3.1.gz", os.F_OK | os.W_OK):
    print("no access to /usr/share/man/man1/asciidoc3.1.gz")
    sys.exit(1)
else:
    os.remove("/usr/share/man/man1/asciidoc3.1.gz")

if not os.access("/usr/share/man/man1/a2x3.1.gz", os.F_OK | os.W_OK):
    print("no access to /usr/share/man/man1/a2x3.1.gz")
    sys.exit(1)
else:
    os.remove("/usr/share/man/man1/a2x3.1.gz")

# remove 'a2x3(.py)'
if not os.access("/usr/bin/a2x3", os.F_OK | os.W_OK):
    print("no access to /usr/bin/a2x3")
    sys.exit(1)
else:
    os.remove("/usr/bin/a2x3")

# remove 'ascidoc3(.py)'
if not os.access("/usr/bin/asciidoc3", os.F_OK | os.W_OK):
    print("no access to /usr/bin/asciidoc3")
    sys.exit(1)
else:
    os.remove("/usr/bin/asciidoc3")
